spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://180.76.173.200:5432/myblog?schema=pulic
    username: postgres
    password: aaaaaa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update